# This file is automatically generated by .github/workflows/build-hds.yml
# Please do not edit it manually, all changes will be overwritten.
{
  nixpkgs = builtins.fetchTarball {
    url = "https://github.com/nixos/nixpkgs/archive/b134951a4c9f3c995fd7be05f3243f8ecd65d798.tar.gz";
    sha256 = "0zydsqiaz8qi4zd63zsb2gij2p614cgkcaisnk11wjy3nmiq0x1s";
  };

  rust-overlay = builtins.fetchTarball {
    url = "https://github.com/oxalica/rust-overlay/archive/275c824ed9e90e7fd4f96d187bde3670062e721f.tar.gz";
    sha256 = "09v299w4ph64sdp0qyybsdn7d78fx1xgg2jj1avxpwyxqi7ildlv";
  };
  rust-version = "1.78.0";

  x86_64-linux.holo-dev-server-bin = builtins.fetchTarball {
    url = "https://github.com/Holo-Host/hds-releases/releases/download/2025-01-09-165434/holo-dev-server-x86_64-linux.tar.gz";
    sha256 = "1imkialhdbjchy1b4zd4j3i1r97g50y44xvw9pwvpzbnwrg721hw";
  };
  aarch64-linux.holo-dev-server-bin = builtins.fetchTarball {
    url = "https://github.com/Holo-Host/hds-releases/releases/download/2025-01-09-165434/holo-dev-server-aarch64-linux.tar.gz";
    sha256 = "0pf8fy2689klhbcyvg5l0416hv3ww52hxxl3y7019pdr5pckg644";
  };
  aarch64-darwin.holo-dev-server-bin = builtins.fetchTarball {
    url = "https://github.com/Holo-Host/hds-releases/releases/download/2025-01-09-165434/holo-dev-server-aarch64-darwin.tar.gz";
    sha256 = "1rg8lk09b135vk2flpfibj5rwgwhylbqk19i4nkw29smc9jd5ny7";
  };
}
